"""Rename target branch to base branch

Revision ID: 036047e5e59d
Revises: 09d5764e9df2
Create Date: 2023-11-15 14:01:59.227191

"""

import alembic


revision = "036047e5e59d"
down_revision = "09d5764e9df2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.execute(
        "ALTER TYPE queuechecksabortcode RENAME VALUE 'TARGET_BRANCH_MISSING' TO 'BASE_BRANCH_MISSING';",
    )
    alembic.op.execute(
        "ALTER TYPE queuechecksabortcode RENAME VALUE 'TARGET_BRANCH_CHANGED' TO 'BASE_BRANCH_CHANGED';",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
