"""remove full name column

Revision ID: 052ea915ffd7
Revises: efa2c2043996
Create Date: 2023-10-03 15:16:58.980312

"""
import alembic


revision = "052ea915ffd7"
down_revision = "efa2c2043996"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.drop_column("github_repository", "full_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
