"""add log_status

Revision ID: 0dc5e36cbd58
Revises: eea03485894a
Create Date: 2023-09-05 17:19:40.066724

"""
import alembic
import sqlalchemy


revision = "0dc5e36cbd58"
down_revision = "eea03485894a"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.execute(
        "CREATE TYPE workflowjoblogstatus AS ENUM ('UNKNOWN', 'GONE', 'ERROR', 'EMBEDDED')"
    )
    alembic.op.add_column(
        "gha_workflow_job",
        sqlalchemy.Column(
            "log_status",
            sqlalchemy.Enum(
                "UNKNOWN",
                "GONE",
                "ERROR",
                "EMBEDDED",
                name="workflowjoblogstatus",
            ),
            server_default="UNKNOWN",
            nullable=False,
        ),
    )
    alembic.op.execute(
        "UPDATE gha_workflow_job SET log_status = 'EMBEDDED' WHERE embedded_log IS NOT NULL"
    )
    alembic.op.create_check_constraint(
        "embedding_linked_columns",
        table_name="gha_workflow_job",
        condition="""
        (
            log_status = 'EMBEDDED' AND log_embedding IS NOT NULL AND embedded_log IS NOT NULL
        ) OR (
            log_status != 'EMBEDDED' AND log_embedding IS NULL AND embedded_log IS NULL
        )
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
