"""Event model action close

Revision ID: 52f21f4b4e6b
Revises: b01cb243b4d1
Create Date: 2023-07-05 15:07:32.732403

"""
import alembic
import sqlalchemy


revision = "52f21f4b4e6b"
down_revision = "b01cb243b4d1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_close",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("message", sqlalchemy.Text(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_close_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_close_pkey"),
        ),
    )
    # ### end Alembic commands ###
