"""Add: gha_workflow_job_log_metadata

Revision ID: 57a7534b63e9
Revises: 036047e5e59d
Create Date: 2023-11-20 16:37:58.405198

"""
import alembic
import sqlalchemy


revision = "57a7534b63e9"
down_revision = "036047e5e59d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "gha_workflow_job_log_metadata",
        sqlalchemy.Column(
            "id",
            sqlalchemy.Integer(),
            autoincrement=True,
            nullable=False,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "workflow_job_id",
            sqlalchemy.BigInteger(),
            nullable=False,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "problem_type",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "language",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "filename",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "lineno",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "error",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "test_framework",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.Column(
            "stack_trace",
            sqlalchemy.String(),
            nullable=True,
            anonymizer_config=None,
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["workflow_job_id"],
            ["gha_workflow_job.id"],
            name=alembic.op.f("gha_workflow_job_log_metadata_workflow_job_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("gha_workflow_job_log_metadata_pkey"),
        ),
    )
    alembic.op.create_index(
        alembic.op.f("gha_workflow_job_log_metadata_workflow_job_id_idx"),
        "gha_workflow_job_log_metadata",
        ["workflow_job_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
