"""add embedding retries columns

Revision ID: 5a96d16ceee3
Revises: 0dc5e36cbd58
Create Date: 2023-09-05 20:49:39.100814

"""
import alembic
import sqlalchemy


revision = "5a96d16ceee3"
down_revision = "0dc5e36cbd58"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.add_column(
        "gha_workflow_job",
        sqlalchemy.Column(
            "log_embedding_attempts",
            sqlalchemy.Integer(),
            server_default="0",
            nullable=False,
            anonymizer_config=None,
        ),
    )
    alembic.op.add_column(
        "gha_workflow_job",
        sqlalchemy.Column(
            "log_embedding_retry_after",
            sqlalchemy.DateTime(),
            nullable=True,
            anonymizer_config=None,
        ),
    )
    alembic.op.create_check_constraint(
        "embedding_retries",
        table_name="gha_workflow_job",
        condition="""
        log_embedding_attempts >= 0 AND (
            ( log_embedding_attempts = 0 AND log_embedding_retry_after IS NULL )
            OR ( log_embedding_attempts > 0 AND log_embedding_retry_after IS NOT NULL)
        )
        """,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
