"""Event model action edit

Revision ID: 616124037cdd
Revises: 6fac7379497e
Create Date: 2023-07-10 10:06:13.441175

"""
import alembic
import sqlalchemy


revision = "616124037cdd"
down_revision = "6fac7379497e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_edit",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("draft", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_edit_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_edit_pkey"),
        ),
    )
    # ### end Alembic commands ###
