"""Add idx_gha_workflow_job_same_job_name_in_repo

Revision ID: 616bd1a47c55
Revises: cee26672ff49
Create Date: 2023-11-06 10:45:41.462004

"""
import alembic


revision = "616bd1a47c55"
down_revision = "cee26672ff49"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        "idx_gha_workflow_job_same_job_name_in_repo",
        "gha_workflow_job",
        ["name_without_matrix", "repository_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
