"""add nullable to blob_url and raw_url of pull_request_file

Revision ID: 61ec48864943
Revises: 82f224f0b3f8
Create Date: 2024-01-11 09:10:15.374070

"""
import alembic
import sqlalchemy


revision = "61ec48864943"
down_revision = "82f224f0b3f8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.alter_column(
        "pull_request_file",
        "blob_url",
        existing_type=sqlalchemy.TEXT(),
        nullable=True,
    )
    alembic.op.alter_column(
        "pull_request_file",
        "raw_url",
        existing_type=sqlalchemy.TEXT(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
