"""Create indexes

Revision ID: 65e800f05671
Revises: 86d40725a53e
Create Date: 2023-12-04 14:15:32.008512

"""
import alembic


revision = "65e800f05671"
down_revision = "86d40725a53e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        alembic.op.f("event_repository_id_idx"),
        "event",
        ["repository_id"],
        unique=False,
    )
    alembic.op.create_index(
        "event_repository_id_type_idx",
        "event",
        ["repository_id", "type"],
        unique=False,
    )
    alembic.op.create_index(
        "event_repository_id_type_received_at_idx",
        "event",
        ["repository_id", "type", "received_at"],
        unique=False,
    )
    alembic.op.create_index(
        alembic.op.f("github_account_login_idx"),
        "github_account",
        ["login"],
        unique=False,
    )
    alembic.op.create_index(
        alembic.op.f("speculative_check_pull_request_event_id_idx"),
        "speculative_check_pull_request",
        ["event_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
