"""Event action queue leave

Revision ID: 732a1510ec1d
Revises: 7995283d5459
Create Date: 2023-07-11 14:16:47.634423

"""
import alembic
import sqlalchemy


revision = "732a1510ec1d"
down_revision = "7995283d5459"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_queue_leave",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("queue_name", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("branch", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("position", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column(
            "queued_at",
            sqlalchemy.DateTime(timezone=True),
            nullable=False,
        ),
        sqlalchemy.Column("partition_name", sqlalchemy.Text(), nullable=True),
        sqlalchemy.Column("merged", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.Column("reason", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column(
            "seconds_waiting_for_schedule",
            sqlalchemy.Integer(),
            nullable=False,
        ),
        sqlalchemy.Column(
            "seconds_waiting_for_freeze",
            sqlalchemy.Integer(),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_queue_leave_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_queue_leave_pkey"),
        ),
    )
    # ### end Alembic commands ###
