"""Event action queue merged

Revision ID: 7995283d5459
Revises: 9f3f9052a5cd
Create Date: 2023-07-10 16:27:15.016390

"""
import alembic
import sqlalchemy


revision = "7995283d5459"
down_revision = "9f3f9052a5cd"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_queue_merged",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("branch", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("queue_name", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column(
            "queued_at",
            sqlalchemy.DateTime(timezone=True),
            nullable=False,
        ),
        sqlalchemy.Column(
            "partition_names",
            sqlalchemy.ARRAY(sqlalchemy.Text(), dimensions=1),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_queue_merged_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_queue_merged_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
