"""Create github_repository table

Revision ID: 7a5673ee5829
Revises: 298d2a2d31b7
Create Date: 2023-04-24 13:56:42.004213

"""
import alembic
import sqlalchemy


revision = "7a5673ee5829"
down_revision = "298d2a2d31b7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "github_repository",
        sqlalchemy.Column(
            "id",
            sqlalchemy.BigInteger(),
            autoincrement=False,
            nullable=False,
        ),
        sqlalchemy.Column("owner_id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("last_dump_at", sqlalchemy.DateTime(), nullable=True),
        sqlalchemy.ForeignKeyConstraint(
            ["owner_id"],
            ["github_account.id"],
            name=alembic.op.f("github_repository_owner_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("github_repository_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
