"""Add base_ref to events

Revision ID: 81392e595d98
Revises: 616bd1a47c55
Create Date: 2023-11-03 16:47:33.935524

"""
import alembic
import sqlalchemy


revision = "81392e595d98"
down_revision = "616bd1a47c55"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.add_column(
        "event",
        sqlalchemy.Column(
            "base_ref",
            sqlalchemy.Text(),
            nullable=True,
            anonymizer_config="anon.lorem_ipsum( characters := 7 )",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
