"""add index on pull_request.head['sha']

Revision ID: 82f224f0b3f8
Revises: 5430e2f0c9c6
Create Date: 2024-01-10 09:19:30.505086

"""
import alembic
import sqlalchemy


revision = "82f224f0b3f8"
down_revision = "5430e2f0c9c6"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        "pull_request_head_sha_gin_idx",
        "pull_request",
        [sqlalchemy.text("(head-> 'sha')")],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
