"""Add event model for action copy

Revision ID: 85830086e719
Revises: ee1a6bd5d698
Create Date: 2023-07-05 12:50:55.410712

"""
import alembic
import sqlalchemy


revision = "85830086e719"
down_revision = "ee1a6bd5d698"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_copy",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("to", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("pull_request_number", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column("conflicts", sqlalchemy.Boolean(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_copy_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_copy_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
