"""add an embedding select index

Revision ID: 8a897f49bb06
Revises: 0dc5e36cbd58
Create Date: 2023-09-07 11:03:26.545991

"""
import alembic


revision = "8a897f49bb06"
down_revision = "5a96d16ceee3"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        "idx_gha_workflow_job_incomplete_job_finder",
        "gha_workflow_job",
        ["conclusion", "log_status", "failed_step_number"],
        unique=False,
        postgresql_where="conclusion = 'FAILURE'::workflowjobconclusion AND failed_step_number IS NOT NULL AND log_status <> ALL (ARRAY['GONE'::workflowjoblogstatus, 'ERROR'::workflowjoblogstatus])",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
