"""add index on pull_request number column

Revision ID: 9442ab168f91
Revises: 8e8dfbc9c805
Create Date: 2023-11-27 14:33:56.060933

"""
import alembic


revision = "9442ab168f91"
down_revision = "8e8dfbc9c805"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        alembic.op.f("pull_request_number_idx"),
        "pull_request",
        ["number"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
