"""Event action queue enter

Revision ID: 9f3f9052a5cd
Revises: d64f676ac24e
Create Date: 2023-07-10 15:02:33.044176

"""
import alembic
import sqlalchemy


revision = "9f3f9052a5cd"
down_revision = "d64f676ac24e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_queue_enter",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("queue_name", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("branch", sqlalchemy.Text(), nullable=False),
        sqlalchemy.Column("position", sqlalchemy.Integer(), nullable=False),
        sqlalchemy.Column(
            "queued_at", sqlalchemy.DateTime(timezone=True), nullable=False
        ),
        sqlalchemy.Column("partition_name", sqlalchemy.Text(), nullable=True),
        sqlalchemy.ForeignKeyConstraint(
            ["id"], ["event.id"], name=alembic.op.f("event_action_queue_enter_id_fkey")
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id", name=alembic.op.f("event_action_queue_enter_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
