"""Add matrix on workflowJob

Revision ID: a4ec6d00ccfa
Revises: 509c35a59731
Create Date: 2023-09-27 11:48:17.592823

"""
import alembic
import sqlalchemy


revision = "a4ec6d00ccfa"
down_revision = "509c35a59731"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.add_column(
        "gha_workflow_job",
        sqlalchemy.Column(
            "matrix", sqlalchemy.String(), nullable=True, anonymizer_config=None
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
