"""Event model action comment

Revision ID: b01cb243b4d1
Revises: 85830086e719
Create Date: 2023-07-05 14:57:12.074602

"""
import alembic
import sqlalchemy


revision = "b01cb243b4d1"
down_revision = "85830086e719"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_comment",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("message", sqlalchemy.Text(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(
            ["id"], ["event.id"], name=alembic.op.f("event_action_comment_id_fkey")
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id", name=alembic.op.f("event_action_comment_pkey")
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
