"""remove unqueue_code column from EventActionQueueChecksEnd

Revision ID: b1059b7235df
Revises: 22c07b729a30
Create Date: 2023-11-09 12:00:58.743139

"""
import alembic


revision = "b1059b7235df"
down_revision = "22c07b729a30"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.drop_column("event_action_queue_checks_end", "unqueue_code")
    alembic.op.execute("DROP TYPE queuechecksunqueuecode")

    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
