"""Event model action dismiss_reviews

Revision ID: c05edaa912c7
Revises: bee9e2dfda9d
Create Date: 2023-07-06 09:34:16.740825

"""
import alembic
import sqlalchemy


revision = "c05edaa912c7"
down_revision = "bee9e2dfda9d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_dismiss_reviews",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column(
            "users",
            sqlalchemy.ARRAY(sqlalchemy.Text(), dimensions=1),
            nullable=False,
        ),
        sqlalchemy.ForeignKeyConstraint(
            ["id"],
            ["event.id"],
            name=alembic.op.f("event_action_dismiss_reviews_id_fkey"),
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id",
            name=alembic.op.f("event_action_dismiss_reviews_pkey"),
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    pass
