"""What have changed

Revision ID: c598a90bd5e4
Revises: 47ea53b21c90
Create Date: 2023-07-12 16:01:39.766410

"""
import alembic
import sqlalchemy


revision = "c598a90bd5e4"
down_revision = "47ea53b21c90"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.alter_column(
        "gha_workflow_job",
        "repository_id",
        existing_type=sqlalchemy.BIGINT(),
        nullable=False,
    )
    alembic.op.alter_column(
        "gha_workflow_run",
        "repository_id",
        existing_type=sqlalchemy.BIGINT(),
        nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
