"""add application access key index

Revision ID: d4a7ed6380c9
Revises: 9662e4efa6ed
Create Date: 2023-10-25 15:31:35.715021

"""
import alembic


revision = "d4a7ed6380c9"
down_revision = "9662e4efa6ed"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_index(
        alembic.op.f("application_api_access_key_idx"),
        "application",
        ["api_access_key"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
