"""Event model action merge

Revision ID: d64f676ac24e
Revises: 7b2a0192424f
Create Date: 2023-07-10 11:51:01.336764

"""
import alembic
import sqlalchemy


revision = "d64f676ac24e"
down_revision = "3857dce77197"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.create_table(
        "event_action_merge",
        sqlalchemy.Column("id", sqlalchemy.BigInteger(), nullable=False),
        sqlalchemy.Column("branch", sqlalchemy.Text(), nullable=False),
        sqlalchemy.ForeignKeyConstraint(
            ["id"], ["event.id"], name=alembic.op.f("event_action_merge_id_fkey")
        ),
        sqlalchemy.PrimaryKeyConstraint(
            "id", name=alembic.op.f("event_action_merge_pkey")
        ),
    )
    # ### end Alembic commands ###
