"""add avatar_url to githubaccount table

Revision ID: e07cd24f7270
Revises: bea98b0de14b
Create Date: 2023-10-17 12:11:02.283061

"""
import alembic
import sqlalchemy
from sqlalchemy.sql import column
from sqlalchemy.sql import table


revision = "e07cd24f7270"
down_revision = "bea98b0de14b"
branch_labels = None
depends_on = None


# Proxy table just to make update request
GitHubAccount = table(
    "github_account",
    column("id", sqlalchemy.BigInteger),
    column("avatar_url", sqlalchemy.String),
)


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.add_column(
        "github_account",
        sqlalchemy.Column(
            "avatar_url",
            sqlalchemy.Text(),
            nullable=True,
            anonymizer_config="anon.lorem_ipsum( words := 7 )",
        ),
    )
    # ### end Alembic commands ###

    alembic.op.execute(
        GitHubAccount.update()
        .where(GitHubAccount.c.avatar_url.is_(None))
        .values(
            avatar_url=f"https://avatars.githubusercontent.com/u/{GitHubAccount.c.id}?v=4",
        ),
    )

    alembic.op.alter_column(
        "github_account",
        "avatar_url",
        nullable=False,
    )


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
