"""remove pull_request-workflow_run association table

Revision ID: e4894ddcace0
Revises: 052ea915ffd7
Create Date: 2023-10-09 09:54:39.699426

"""
import alembic


revision = "e4894ddcace0"
down_revision = "052ea915ffd7"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    alembic.op.drop_table("jt_gha_workflow_run_pull_request")
    # ### end Alembic commands ###


def downgrade() -> None:
    # NOTE(sileht): We don't want to support downgrades as it means we will
    # drop columns. And we don't want to provide tooling that may drop data.
    # For restoring old version of the database, the only supported process is
    # to use a backup.
    pass
