sources:
  python-version:
    name: Get latest Python version from Docker Hub
    kind: shell
    spec:
      command: python3 .github/get-latest-python-version.py

  datadog-agent-version:
    name: Get the latest datadog-agent version from apt
    kind: shell
    spec:
      command: bash .github/get-latest-datadog-agent-version.sh

targets:
  # PYTHON VERSION
  heroku_runtime.txt:
    name: "Update runtime.txt"
    kind: file
    sourceID: python-version
    spec:
      file: runtime.txt
      forcecreate: true
      content: python-{{ source `python-version` }}
  tox-basepython:
    name: "Update tox.ini basepython"
    kind: file
    sourceID: python-version
    spec:
      file: tox.ini
      lineMatchPattern: "(basepython = python)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2
  tox-python3.X:
    name: "Update tox.ini python3.X version"
    kind: file
    sourceID: python-version
    spec:
      file: tox.ini
      lineMatchPattern: "(.*python)(3.\\d+)(^\\d)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2
  tox-py3X:
    name: "Update tox.ini py3 version"
    kind: file
    sourceID: python-version
    spec:
      file: tox.ini
      lineMatchPattern: "(.*py)(3\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replacer:
          from: "."
          to: ""
      - replaceRegexGroup: 2
  ci-file-tox:
    name: "Update CI file GitHub workflow"
    kind: file
    sourceID: python-version
    spec:
      file: ".github/workflows/ci.yaml"
      lineMatchPattern: "(\\s+tox -e py)(3\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replacer:
          from: "."
          to: ""
      - replaceRegexGroup: 2
  ci-file-python-version:
    name: "Update CI file GitHub workflow"
    kind: file
    sourceID: python-version
    spec:
      file: ".github/workflows/ci.yaml"
      lineMatchPattern: "(\\s+python-version: )(.+)"
    transformers:
      - replaceRegexGroup: 2
  ci-record-file:
    name: "Update ci-record file GitHub workflow"
    kind: file
    sourceID: python-version
    spec:
      file: ".github/workflows/ci-record.yaml"
      lineMatchPattern: "(\\s+python-version: )(.+)"
    transformers:
      - replaceRegexGroup: 2
  # DATADOG AGENT VERSION
  datadog-agent-version-txt:
    name: "Update datadog/agent-version.txt"
    kind: file
    sourceID: datadog-agent-version
    spec:
      file: datadog/agent-version.txt
      forcecreate: true
      content: "{{ source `datadog-agent-version` }}"
  dockerfile:
    name: "Update DD_AGENT_VERSION in Dockerfile"
    sourceID: datadog-agent-version
    kind: file
    spec:
      file: Dockerfile
      lineMatchPattern: "^ARG DD_AGENT_VERSION="
    transformers:
      - addPrefix: "ARG DD_AGENT_VERSION="
  pyproject.toml-py3X:
    name: "Update pyproject.toml py3X target-version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(target-version = .*py)(3\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replacer:
          from: "."
          to: ""
      - replaceRegexGroup: 2
  pyproject.toml-python-version:
    name: "Update pyproject.toml python version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(python = \">=)(3\\.\\d+)(,<4.0\")"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2
  pyproject.toml-classifers-py-version:
    name: "Update pyproject.toml python classifier version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(classifiers = .*)(3\\.\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2
