sources:
  python-version:
    name: Get latest Python version from Docker Hub
    kind: shell
    spec:
      command: python3 .github/get-latest-python-version.py

  datadog-agent-version:
    name: Get the latest datadog-agent version from apt
    kind: shell
    spec:
      command: bash .github/get-latest-datadog-agent-version.sh

  datadog-mergify-integration-version:
    name: Get the latest datadog-mergify version from datadog wheels
    kind: shell
    spec:
      command: python3 .github/get-latest-datadog-mergify-integration-version.py

  actionlint-version:
    name: Get latest action lint version from GitHub release
    kind: shell
    spec:
      # yamllint disable-line rule:line-length
      command: bash -c "curl https://api.github.com/repos/rhysd/actionlint/releases?per_page=1 | jq -r .[0].name[1:]"

  overmind-version:
    name: Get latest overmind version from GitHub release
    kind: shell
    spec:
      # yamllint disable-line rule:line-length
      command: bash -c "curl https://api.github.com/repos/DarthSim/overmind/releases?per_page=1 | jq -r .[0].tag_name[1:]"

targets:
  # PYTHON VERSION
  heroku_runtime.txt:
    name: "Update runtime.txt"
    kind: file
    sourceID: python-version
    spec:
      file: runtime.txt
      forcecreate: true
      content: python-{{ source `python-version` }}
  github-workflow-python-version:
    name: "Update CI file GitHub workflow"
    kind: file
    sourceID: python-version
    spec:
      files:
        - ".github/workflows/ci.yaml"
        - ".github/workflows/ci-record.yaml"
        - ".github/workflows/api-schemas-upload.yaml"
        - ".github/actions/tooling-setup/action.yml"
      lineMatchPattern: "(\\s+python-version: )(.+)"
    transformers:
      - replaceRegexGroup: 2
  # DATADOG AGENT VERSION
  datadog-agent-version-txt:
    name: "Update datadog/agent-version.txt"
    kind: file
    sourceID: datadog-agent-version
    spec:
      file: datadog/agent-version.txt
      forcecreate: true
      content: "{{ source `datadog-agent-version` }}"
  dockerfile-dd-agent:
    name: "Update DD_AGENT_VERSION in dockerfiles/Dockerfile.common"
    sourceID: datadog-agent-version
    kind: file
    spec:
      file: dockerfiles/Dockerfile.common
      lineMatchPattern: "^ARG DD_AGENT_VERSION="
    transformers:
      - addPrefix: "ARG DD_AGENT_VERSION="
  pyproject.toml-py3X:
    name: "Update pyproject.toml py3X target-version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(target-version = .*py)(3\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replacer:
          from: "."
          to: ""
      - replaceRegexGroup: 2
  pyproject.toml-python-version:
    name: "Update pyproject.toml python version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(python = \"~)(3\\.\\d+)(\")"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2
  pyproject.toml-classifers-py-version:
    name: "Update pyproject.toml python classifier version"
    kind: file
    sourceID: python-version
    spec:
      file: pyproject.toml
      lineMatchPattern: "(classifiers = .*)(3\\.\\d+)(.*)"
    transformers:
      - find: "^\\d+\\.\\d+"
      - replaceRegexGroup: 2

  # DATADOG MERGIFY INTEGRATION VERSION
  dockerfile-dd-mergify:
    name: "Update DD_MERGIFY_VERSION in dockerfiles/Dockerfile.common"
    sourceID: datadog-mergify-integration-version
    kind: file
    spec:
      file: dockerfiles/Dockerfile.common
      lineMatchPattern: "^ARG DD_MERGIFY_VERSION="
    transformers:
      - addPrefix: "ARG DD_MERGIFY_VERSION="
  datadog-mergify-integration-version-txt:
    name: "Update datadog/agent-version.txt"
    kind: file
    sourceID: datadog-mergify-integration-version
    spec:
      file: datadog/mergify-integration-version.txt
      forcecreate: true
      content: "{{ source `datadog-mergify-integration-version` }}"

  # ACTIONLINT VERSION
  github-workflow-actionlint-version:
    name: "Update CI file GitHub workflow"
    kind: file
    sourceID: actionlint-version
    spec:
      files: [".github/workflows/ci.yaml"]
      lineMatchPattern: "(\\s+run: bash.*download-actionlint.bash\\) )(.+)"
    transformers:
      - replaceRegexGroup: 2
  overmind-version:
    name: "Update overmind version"
    kind: file
    sourceID: overmind-version
    spec:
      file: dockerfiles/Dockerfile.onpremise.footer
      lineMatchPattern: "^ARG OVERMIND_VERSION="
    transformers:
      - addPrefix: "ARG OVERMIND_VERSION="
