version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
    open-pull-requests-limit: 10
    allow:
      - dependency-name: "*"
        dependency-type: all
    ignore:
      # FIXME(sileht):
      # https://github.com/redis/redis-py/issues/2995
      - dependency-name: redis
      # FIXME(leo): 2.3.0 has some incompatibility issues
      # https://linear.app/mergify/issue/MRGFY-2933/ddtrace-230-errors
      - dependency-name: ddtrace
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      # yamllint disable-line rule:quoted-strings
      time: "08:00"
      timezone: Europe/Paris
