excluded-packages:
  # unused mandatory system package
  - libldap
  - libldap-common
  - apt
  - apt-transport-https
  - libapt-pkg6.0
  - systemd
  - systemd-sysv
  - systemd-timesyncd
  - libkrb5support0
  - libx11-data
  - ncurses-term
  - ncurses-bin
  - ncurses-base
