rules:
  - id: postgres-url
    category: databases
    title: Postgres URL
    severity: CRITICAL
    keyword:
      - postgres
    regex: postgres:\/\/(\w+):(\w+)@([a-zA-Z0-9\-\.]+):(\d+)\/(\w+)(?:\?sslmode=(\w+))?
  - id: redis-url
    category: databases
    title: Redis URL
    severity: CRITICAL
    keyword:
      - redis
    regex: redis:\/\/(?:(\w+):(\w+)@)?([a-zA-Z0-9\-\.]+)(?::(\d+))?(?:\/(\d+))?
disable-allow-rules:
  - tests
