version: "3.1"
services:
  redis:
    image: redis
    ports:
      - "${LOCAL_REDIS_PORT:-0}:6379"
    # NOTE(greesb): This is to allow parallel testing.
    # Since, at the moment, we have only 10 redis databases we can
    # only execute 10 parallel tests at a time (since each test as its own databases).
    # If we need more than that, we might need to increment this or
    # make it a parameter in the run-tests.sh somehow.
    command: --databases 1000
  postgres:
    image: postgres
    ports:
      - "${LOCAL_POSTGRES_PORT:-0}:5432"
    environment:
      POSTGRES_PASSWORD: password
