version: "3.1"
services:
  google_cloud_storage:
    image: fsouza/fake-gcs-server
    ports:
      - "${LOCAL_GCS_PORT:-0}:8000"
    command: -scheme http -port 8000
  redis:
    image: redis
    ports:
      - "${LOCAL_REDIS_PORT:-0}:6379"
    # NOTE(greesb): This is to allow parallel testing.
    # Since, at the moment, we have only 10 redis databases we can
    # only execute 10 parallel tests at a time (since each test as its own databases).
    # If we need more than that, we might need to increment this or
    # make it a parameter in the run-tests.sh somehow.
    command: --databases 1000
  postgres:
    image: ankane/pgvector:v0.4.4
    ports:
      - "${LOCAL_POSTGRES_PORT:-0}:5432"
    environment:
      POSTGRES_PASSWORD: password
