[tool.poe.executor]
type = "poetry"

[tool.poe.env]
DD_DOGSTATSD_DISABLE = "1"
DD_TRACE_ENABLED = "0"
MERGIFYENGINE_TEST_SETTINGS.default = "fake.env"
PYTEST_TIMEOUT = "200"

[tool.poe.tasks.shell]
deps = ["setup"]
executor = { type  = "simple" }
cmd = "./tools/run-tests.sh poetry shell"
[tool.poe.tasks.shell.env]
VIRTUAL_ENV_DISABLE_PROMPT = ""
PS1 = '\[\033[01;32m\]\u@\h\[\033[00m\]:\[\033[01;34m\]\w\[\033[00m\]\$ '

[tool.poe.tasks.linters]
deps = ["setup"]
help = "Run linters"
default_item_type = "cmd"
sequence = [
  "ruff check .",
  "ruff format --check .",
  "mypy",
  "yamllint .",
  "reno lint",
  "tools/import-checks.sh",
  "tools/check-obsolete-fixtures.sh",
  "bash -n onpremise/entrypoint.sh",
  "bash -n datadog-wrapper.sh"
]

[tool.poe.tasks.test]
deps = ["setup"]
help = "Run test suite"
cmd = "./tools/run-tests.sh pytest -v --timeout_method thread --reruns 3 --only-rerun MissingEventTimeout"

[tool.poe.tasks.test-parallel]
deps = ["setup"]
help = "Run test suite in parallel"
cmd = "./tools/run-tests.sh pytest -vv --timeout_method thread -n auto"

[tool.poe.tasks.record]
deps = ["setup"]
help = "Record test suite fixtures"
cmd = "./tools/run-tests.sh pytest -v --timeout_method thread mergify_engine/tests/functional"
[tool.poe.tasks.record.env]
MERGIFYENGINE_TEST_SETTINGS = "test.env"
MERGIFYENGINE_TESTING_RECORD = "1"
MERGIFYENGINE_TESTING_RECORD_EVENTS_WAITING_TIME.default = "30"
DD_DOGSTATSD_DISABLE = "1"
DD_TRACE_ENABLED = "0"
PYTEST_TIMEOUT = "3600"

[tool.poe.tasks.record-parallel]
deps = ["setup"]
help = "Record test suite fixtures in parallel"
cmd = "./tools/run-tests.sh pytest -vv --timeout_method thread -n auto --dist=loadgroup mergify_engine/tests/functional"
[tool.poe.tasks.record-parallel.env]
MERGIFYENGINE_TEST_SETTINGS = "test.env"
MERGIFYENGINE_TESTING_RECORD = "1"
MERGIFYENGINE_TESTING_RECORD_EVENTS_WAITING_TIME.default = "180"
DD_DOGSTATSD_DISABLE = "1"
DD_TRACE_ENABLED = "0"
PYTEST_TIMEOUT = "5400"

[tool.poe.tasks.import-checks]
help = "Run python import checks"
default_item_type = "cmd"
sequence = [
    # Ensure no dev deps are installed like in production
    "poetry install --only main --sync",
    "./tools/import-checks.sh",
]
[tool.poe.tasks.import-checks.env]
MERGIFYENGINE_SENTRY_URL = "https://12345@localhost/12345"
MERGIFYENGINE_SENTRY_ENVIRONMENT = "ci"
DD_API_KEY = "testing-false-key"

[tool.poe.tasks.serve]
deps = ["setup"]
help = "Start mergify-engine workers and API"
cmd = "./tools/run-tests.sh ./tools/serve.sh"
use_exec = true
[tool.poe.tasks.serve.env]
PYTHONUNBUFFERED = "1"
DD_DOGSTATSD_DISABLE = "1"
DD_REMOTE_CONFIGURATION_ENABLED = "0"
DD_TRACE_ENABLED = "0"
MERGIFYENGINE_API_ENABLE = "1"
MERGIFYENGINE_HTTP_TO_HTTPS_REDIRECT = "0"
MERGIFYENGINE_TEST_SETTINGS = "test.env"
MERGIFYENGINE_DASHBOARD_UI_FEATURES = "subscriptions;applications;intercom;statuspage"
MERGIFYENGINE_DASHBOARD_UI_FRONT_BACKEND_URL = "http://localhost:8802"
MERGIFYENGINE_SUBCRIPTION_BASE_URL = "http://localhost:5001"

[tool.poe.tasks.api-schemas]
deps = ["setup"]
help = "Build API schemas"
cmd = "./tools/build-api-schemas.sh"

[tool.poe.tasks.docker]
help = "Build docker images (eg: -t my-testing-image --target saas-web)"
cmd = "./tools/docker-build-dev.sh"

[tool.poe.tasks.semgrep]
deps = ["setup"]
help = "Run SAST tools"
cmd = "semgrep --config=auto --error --timeout=15"

[tool.poe.tasks.setup]
help = "Sync poetry virtualenv"
executor = { type  = "simple" }
default_item_type = "cmd"
sequence = [
    "./tools/poetry-ci-install.sh",
    "./tools/brew-requirements.sh"
]

[tool.poe.tasks.revision]
deps = ["setup"]
help = "Create a database revision file"
cmd = "./tools/run-tests.sh ./tools/run-alembic-revision.sh"

[tool.poe.tasks.alembic]
deps = ["setup"]
help = "Run an alembic command"
cmd = "./tools/run-tests.sh alembic --config mergify_engine/models/db_migration/alembic.ini"

[tool.poe.tasks.pg_anonymizer]
deps = ["setup"]
help = "Generate and check the rule file for postgresql_anonymizer"
default_item_type = "cmd"
sequence = [
     "./tools/run-tests.sh python3 mergify_engine/models/anonymizer.py",
     "docker build -t mergifyio/custom_postgresql_anonymizer -f dockerfiles/Dockerfile.postgresql_anonymizer .",
     "bash -c 'cat empty_database.sql postgresql_anonymizer_rules.sql | docker run -e LANG=C --rm -i mergifyio/custom_postgresql_anonymizer /anon-custom.sh'"
]
