# This is only a pg 14 but it's good enough for now
FROM registry.gitlab.com/dalibo/postgresql_anonymizer:latest

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update -y && apt-get upgrade -y && apt-get install -y postgresql-14-pgvector && apt-get autoremove --purge -y
