name: Changelog sync

on:
  pull_request_target:
    branches:
      - main
    types:
      - closed
      - labeled

permissions: read-all

jobs:
  changelog_sync:
    if: >
      github.event.pull_request.merged == true
      && contains( github.event.pull_request.labels.*.name, 'need changelog')
    runs-on: ubuntu-latest
    steps:
      - name: Synchronize changelog
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: Mergifyio/gha-changelog-syncer@main
        with:
          NOTION_API_KEY: ${{ secrets.CHANGELOG_NOTION_API_KEY }}
          NOTION_DATABASE_ID: ${{ secrets.CHANGELOG_NOTION_DATABASE_ID }}
