name: Clifus
permissions: write-all

on:
  workflow_dispatch:
  schedule:
    - cron: 0 0 * * *

jobs:
  python-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # yamllint disable-line rule:line-length
      # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - uses: Mergifyio/clifus@main
        with:
          NAME: Python
          SOURCE: python-version
          GITHUB_TOKEN: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          LABELS: python,dependencies
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}

  datadog-agent-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # yamllint disable-line rule:line-length
      # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - uses: Mergifyio/clifus@main
        with:
          NAME: Datadog agent
          SOURCE: datadog-agent-version
          GITHUB_TOKEN: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          LABELS: dependencies
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}

  datadog-mergify-integration-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # yamllint disable-line rule:line-length
      # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - uses: Mergifyio/clifus@main
        with:
          NAME: Datadog Mergify integration
          SOURCE: datadog-mergify-integration-version
          GITHUB_TOKEN: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          LABELS: dependencies
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}

  actionlint-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # yamllint disable-line rule:line-length
      # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - uses: Mergifyio/clifus@main
        with:
          NAME: Actionlint
          SOURCE: actionlint-version
          GITHUB_TOKEN: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          LABELS: dependencies
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}

  overmind-version-bump:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      # yamllint disable-line rule:line-length
      # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
      - uses: Mergifyio/clifus@main
        with:
          NAME: Overmind
          SOURCE: overmind-version
          GITHUB_TOKEN: ${{ secrets.MERGIFY_CI_BOT_PAT }}
          LABELS: dependencies
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}
