# yamllint disable rule:line-length
name: Create Docs Linear Issue on PR merge
on:
  pull_request:
    types: [closed]
jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'need documentation')
    steps:
      - name: Create issue in Linear
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          JSON_PAYLOAD=$(jq -n \
                          --arg title "Docs for $PR_TITLE" \
                          --arg desc "Documentation needed for merged PR: $PR_URL" \
                          --arg teamId "MRGFY" \
                          --arg labelId "documentation" \
                          '{
                            "query": "mutation ($title: String!, $description: String!, $teamId: String!, $labelId: String!) { issueCreate(input: { title: $title, description: $description, teamId: $teamId, labelIds: [$labelId], statusId: \"status_todo\" }) { success issue { id title } } }",
                            "variables": {
                              "title": $title,
                              "description": $desc,
                              "teamId": $teamId,
                              "labelId": $labelId
                            }
                          }')
          curl -X POST "https://api.linear.app/graphql" \
          -H "Authorization: Bearer ${{ secrets.LINEAR_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "$JSON_PAYLOAD"
