# yamllint disable rule:line-length
name: Create Docs Linear Issue on PR merge
on:
  pull_request:
    types: [closed]
jobs:
  create_issue:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'need documentation')
    steps:
      - name: Create issue in Linear
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          PR_URL: ${{ github.event.pull_request.html_url }}
        run: |
          curl -X POST "https://api.linear.app/graphql" \
          -H "Authorization: Bearer ${{ secrets.LINEAR_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d "
          {
            \"query\": \"mutation($title: String!, $description: String!, $teamId: String!, $labelId: String!) { createIssue(input: { title: $title, description: $description, teamId: $teamId, labelIds: [$labelId], statusId: \\\"status_todo\\\" }) { issue { id } } }\",
            \"variables\": {
              \"title\": \"Docs for $PR_TITLE\",
              \"description\": \"Documentation needed for merged PR: $PR_URL\",
              \"teamId\": \"MRGFY\",
              \"labelId\": \"documentation\"
            }
          }"
