name: mergify-engine syncer cron
permissions: write-all
on:
  workflow_dispatch:

jobs:
  syncer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd ./.github/actions/syncer
          yarn install
      - uses: ./.github/actions/syncer
        with:
          token-write: ${{ secrets.GITHUB_TOKEN }}
          token-read: ${{ secrets.DEPLOY_BOT_PAT_TOKEN_FOR_SYNCER }}
          repository: mergify-engine
          production: true
