name: Testing database sync
permissions: read-all
on:
  workflow_dispatch:
  #  schedule:
  #  - cron: "30 6 * * 1"

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true

jobs:
  testing-database-sync:
    timeout-minutes: 30
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      id-token: write
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup AWS credentials
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: aws-actions/configure-aws-credentials@v4.0.1
        with:
          role-to-assume: arn:aws:iam::912098512391:role/OIDC_RDS@engine_ci
          aws-region: us-east-1

      - name: Prepare MERGIFYENGINE_DATABASE_URL
        id: PRODUCTION_DATABASE_BASE_URL
        env:
          PRODUCTION_DATABASE_HOST: ${{ vars.PRODUCTION_DATABASE_HOST }}
          PRODUCTION_DATABASE_PORT: ${{ vars.PRODUCTION_DATABASE_PORT }}
          PRODUCTION_DATABASE_USERNAME: ${{ vars.PRODUCTION_DATABASE_USERNAME }}
        run: |
          URL="$(tools/build-production-database-base-url.sh)"
          echo "::add-mask::$URL"
          echo "PRODUCTION_DATABASE_BASE_URL=$URL" >> "$GITHUB_OUTPUT"

      - name: Syncing databases
        env:
          PRODUCTION_DATABASE_BASE_URL: |-
            ${{ steps.PRODUCTION_DATABASE_BASE_URL.outputs.PRODUCTION_DATABASE_BASE_URL }}
        run: |
          # NOTE(sileht): maybe run this on AWS Lambda to avoid the network roundtrip
          # between AWS and GitHub Actions
          docker run \
            --rm \
            -v "$(pwd):/app" \
            -e PRODUCTION_DATABASE_BASE_URL \
            -u postgres \
            ankane/pgvector:v0.4.4 \
            /app/tools/run-testing-database-sync.sh

      - name: Report Status
        if: failure() && github.event_name != 'pull_request'
        # yamllint disable-line rule:line-length
        # nosemgrep: yaml.github-actions.security.third-party-action-not-pinned-to-commit-sha.third-party-action-not-pinned-to-commit-sha
        uses: Mergifyio/gha-slack-notification@main
        with:
          message: Database sync testing
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WORKFLOWS_WEBHOOK_URL }}
